version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
    container_name: booking-app
    ports:
      - 8080:8080
    # command: ./mvnw spring-boot:run
    volumes:
      - ./:/workspace/app
      - ./.docker/springboot:/workspace/app/src/main/resources
    depends_on:
      - db
    networks:
      - booking-network

  db:
    image: postgres:16.2-alpine
    container_name: booking-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=booking
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d booking" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./data:/var/lib/postgresql/data
    # restart: always
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge
