spring:
  # profiles:
  #   active:
    # - dev
  devtools:
    livereload:
      enabled: true
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: "true"
    open-in-view: false
    show-sql: true